# Meta Data for SEO

## Homepage
title = "Plubo"
titleSeparator = "-"
titleAddition = "A simple WordPress plugin boilerplate"
description = "Plubo is a WordPress plugin boilerplate with some useful scripts to speed up your development."

## Documentation
docsVersion = "0.1"

## Open Graph
images = ["images/plubo.png"]
ogLocale = "en_US"
domainTLD = "plubo.dev"
titleHome = "PLUBO"

## Twitter Cards
#twitterSite = "@getdoks"
twitterCreator = "@manganomenseki"

## JSON-LD
schemaType = "Person"
# schemaType = "Organization"
schemaName = "Plubo"
schemaAuthor = "Joan Rodas"
schemaAuthorTwitter = "https://twitter.com/manganomenseki"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/joan-rodas-cusid%C3%B3-066346122/"
schemaAuthorGitHub = "https://github.com/joanrodas"
schemaLocale = "en-US"
schemaLogo = "images/logo-plubo.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "images/plubo.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaLinkedIn = ""
schemaGitHub = "https://github.com/joanrodas/plubo"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2022 Joan Rodas"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "WordPress plugin boilerplate"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
docsRepo = "https://github.com/joanrodas/plubo"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = false
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
